### ISSUE TITLE
you could do a how 2 pls :)

### ISSUE THREAD

**Issue by Berny-Design** [crea-doo/nokia-3310-contact-converter#1]
please

**Comment by crea-doo** [comment]
So basically it's pretty easy:
* Have Java 8 (or newer) installed
* Run the `build.bat` or `build.sh` and wait for the build to finish
* Run the `convert.bat` or `convert.sh` (use param `--help` to get usage info)

For a short (german) description look over to [this forum thread](https://www.fjsoft.at/forum/viewtopic.php?p=126121)

**Comment by Berny-Design** [comment]
Error: JAVA_HOME not found in your environment.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Press any key to continue . . .

I always get this problem

**Comment by crea-doo** [comment]
Then please first properly configure your system/Java installation - some results from Google:
* https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html
* https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/

Maybe you also will have to restart after setting the environment variable - but then it should hopefully work...

**Comment by Berny-Design** [comment]
yeah I did that about 10 times :D

**Comment by Berny-Design** [comment]
I dont know why but it always is sth wrong now:
Error: Could not find or load main class Klug\Desktop\erwin
Caused by: java.lang.ClassNotFoundException: Klug\Desktop\erwin

thats my file, maybe sth is wrong with that...
or could you export it ? :/

https://mega.nz/#!RngSwIwb!junu5QxJ9Q3MXnxlDeKyh3j6h-2fbwPSycWyfyVUpKs

**Comment by crea-doo** [comment]
I think there are spaces in your path - like C:\Users\What Ever\Desktop\xxx\yyy zzz\
Just try to wrap quotes around your input-/outputfile (like "C:\Users\What Ever\Desktop\xxx\yyy zzz\file.xyz") or try to move the repo to a folder without spaces in the path and try again...

**Comment by crea-doo** [comment]
If you finally managed to use the tool, some kind of information would be great...

**Comment by Berny-Design** [comment]
Wasn’t possible. I typed them all.
